api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', api_preview, name='home'),
    path('page', PostEndPoint.as_view(), name='post-list'),
    path('page/<int:pk>', post_detail_end_point, name='post-detail'),
    path('product', ProductEndPoint.as_view(), name='product-list'),
    path('product/<pk>', product_detail_end_point, name='pro-detail'),
    path('media', MediaEndPoint.as_view(), name='media'),
    path('media/<pk>', media_detail_emd_point, name='media-detail'),
]

beauty/urls.py
from django.urls import path
from .views import *

app_name = 'beauty'

urlpatterns = [
    path('', MainPage.as_view(), name='home'),
    path('post-list', PageListView.as_view(), name='list'),
    path('add-subs', AddSubscriber.as_view(), name='add-subs'),
    path('<link>/comment', AddComment.as_view(), name='add-comment'),
    path('<link>/like', add_likes, name='like'),
]

urlpatterns += [
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/update', UpdateProfileView.as_view(), name='update-profile'),
    path('profile/address', AddressList.as_view(), name='address-list'),
    path('profile/address/create', AddAddressView.as_view(), name='add-address'),
    path('profile/address/<slug:address_link>', UpdateAddress.as_view(), name='update-address'),
    path('profile/address/<slug:addderss_link>/delete', AddressDelete.as_view(), name='delete-address'),
]

urlpatterns += [
    path('products', ProductList.as_view(), name='pro-list'),

]

""" URL for Page detail """
urlpatterns += [
    path('product/<p_link>/comment', CreateProductComment.as_view(), name='pro-comment'),
    path('product/<p_link>/like', pro_likes, name='pro-like'),
    path('product/<p_link>', ProductDetail.as_view(), name='pro-detail'),
    path('<link>', PageDetail.as_view(), name='detail'),
]

beauty_care/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from backend.sitemaps import PostSitemaps, ProductsSitemaps


sitemaps = {
    'post': PostSitemaps,
    'product': ProductsSitemaps
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('order/', include('commerce.urls', namespace='com')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
    path('wpcp-admin/', include('backend.urls', namespace="my")),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [path('', include('beauty.urls', namespace='beauty'))]

commerce/urls.py
from django.urls import path
from .views import *

app_name = 'com'

urlpatterns = [
    path('', OrderSummary.as_view(), name='order'),
    path('add-to-cart/<p_link>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<p_link>', remove_from_cart, name='remove-from-cart'),
    path('reduce/<p_link>', reduce_item, name='reduce-item'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('payment/success/<int:pk>', PaymentSuccess.as_view(), name='payment-success'),
    path('payment/cancel', PaymentCancel.as_view(), name='payment-cancel'),
    path('payment/<method>', PaymentView.as_view(), name='payment'),
    path('webhook/stripe', stripe_webhook, name='stripe-webhook')
]

""" url for ordered item """

urlpatterns += [
    path("ordered", MyOrderedItem.as_view(), name="ordered-item"),
    path('ordered/on-going', MyOngoingItem.as_view(), name='on-going-item'),
    path('ordered/ship/<slug:reff>', SeeReceipt.as_view(), name='receipt-detail'),
]

beauty/forms.py
from django import forms
from .models import Subscriber, PostComment, ProductComment, Address, UserProfile
from django.contrib.auth.models import User


class AddSubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['name', 'comment']


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['post_code', 'main_address', 'detailed_address', 'mark_as']


class AddProductCommentForm(forms.ModelForm):
    class Meta:
        model = ProductComment
        fields = ['name', 'comment']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'image']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class UpdateAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['phone', 'post_code', 'main_address', 'detailed_address', 'default', 'mark_as']

        widget = {
            'phone': forms.TextInput(attrs={'placeholder': 'Fill this field if you have different phone number'}),
            # 'phone': forms.TextInput(attrs={'placeholder': 'Fill this field if you have different phone number'})
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['phone'].widgets.attrs.update({'placeholder': 'Fill this field if you have different phone number'})

beauty/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.generic import *
from backend.models import Profile, Post, ProductReview
from .forms import *
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Q as __
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .utils import link_generator, address_default
from django.contrib import messages
links = 'link'
p_links = 'p_link'


class MainPage(TemplateView):
    template_name = 'beauty/main.html'

    def get_context_data(self, **kwargs):
        context = super(MainPage, self).get_context_data(**kwargs)
        profile = get_object_or_404(Profile, pk=1)
        latest = Post.objects.all()[:3]
        pro_latest = ProductReview.objects.all()[:3]

        context['products'] = pro_latest
        context['profile'] = profile
        context['latest'] = latest
        return context


class AddressList(ListView):
    model = Address
    template_name = 'beauty/address.html'
    ordering = '-id'
    paginate_by = 10
    context_object_name = 'address'

    def get_queryset(self):
        return Address.objects.filter(user=self.request.user).order_by(self.ordering)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(AddressList, self).dispatch(request, *args, **kwargs)


class AddAddressView(View):
    model = Address
    template_name = 'beauty/forms.html'
    form_class = AddAddressForm

    def get(self, *args, **kwargs):
        context = {
            'form': self.form_class
        }
        return render(self.request, self.template_name, context)
    
    def post(self, *args, **kwargs):
        url = self.request.GET.get('url')
        form = self.form_class(self.request.POST or None)
        if form.is_valid():
            link = link_generator(12)
            address = Address.objects.all()
            add_link = [x.address_link for x in address]

            while True:
                if link in add_link:
                    link = link_generator(12)
                else:
                    break

            default = address_default(self.request)
            if not default:
                form.instance.default = True

            form.instance.address_link = link
            form.instance.user = self.request.user
            form.save()

        return redirect(url) if url and url is not None else redirect('beauty:address-list')

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(AddAddressView, self).dispatch(request, *args, **kwargs)


class UpdateAddress(UpdateView):
    model = Address
    template_name = 'beauty/forms.html'
    form_class = UpdateAddressForm
    query_pk_and_slug = True
    slug_field = 'address_link'
    slug_url_kwarg = 'address_link'

    def get_success_url(self):
        return reverse('beauty:address-list')


class AddressDelete(DeleteView):
    model = Address
    template_name = 'beauty/forms.html'
    query_pk_and_slug = True
    slug_field = 'address_link'
    slug_url_kwarg = 'address_link'

    def get_success_url(self):
        return reverse('beauty:address-list')


class AddSubscriber(CreateView):
    model = Subscriber
    form_class = AddSubscriberForm
    template_name = 'beauty/sub.html'


class PageDetail(DetailView):
    model = Post
    template_name = 'beauty/detail.html'
    context_object_name = 'post'
    query_pk_and_slug = True
    slug_field = links
    slug_url_kwarg = links

    def get_context_data(self, **kwargs):
        context = super(PageDetail, self).get_context_data(**kwargs)
        form = AddCommentForm
        this = get_object_or_404(Post, link=self.kwargs[links])
        comments = PostComment.objects.filter(post=this)
        pro_post = True

        context['form'] = form
        context['pro_post'] = pro_post
        context['comments'] = comments
        return context


class PageListView(ListView):
    model = Post
    context_object_name = 'post'
    template_name = 'beauty/list.html'
    ordering = '-id'
    paginate_by = 5

    def get_queryset(self):
        q = self.request.GET.get('q')
        post = Post.objects.all()
        if q is not None:
            post = Post.objects.filter(
                __(title__icontains=q) | __(content__icontains=q) |
                __(desc__icontains=q) | __(keyword__icontains=q)
            ).order_by(self.ordering)
            return post
        else:
            return post

    def get_context_data(self, **kwargs):
        context = super(PageListView, self).get_context_data(**kwargs)
        pd = self.request.GET.get('pd')
        if pd is not None:
            if pd == '1':
                desk = True
            else:
                desk = False

        else:
            desk = True

        context['desk'] = desk
        return context


class UpdateProfileView(View):
    def get(self, *args, **kwargs):
        user = self.request.user
        profile = UserProfile.objects.filter(user=user)
        form = UserForm(instance=user)
        e_form = UserProfileForm(instance=profile[0]) if profile.exists() else UserProfileForm()

        context = {
            'form': form,
            'e_form': e_form,
        }

        return render(self.request, 'beauty/pr_form.html', context)

    def post(self, *args, **kwargs):
        user = self.request.user
        form = UserForm(self.request.POST or None, instance=user)
        profile = UserProfile.objects.filter(user=user)
        e_form = UserProfileForm(self.request.POST or None, self.request.FILES or None, instance=user) if profile.exists() else UserProfileForm(self.request.POST or None, self.request.FILES or None)

        if form.is_valid():
            form.save()
            if e_form.is_valid():
                phone = e_form.cleaned_data['phone']
                image = e_form.cleaned_data['image']
                e_user = UserProfile.objects.filter(user=user)[0]
                if not e_user:
                    UserProfile(user=user, phone=phone, image=image).save()
                else:
                    e_user.phone = phone
                    e_user.image = image
                    e_user.user = user
                    e_user.save()
                messages.info(self.request, "Profile Updated ! ")

        return redirect('beauty:profile')

    # @method_decorator(login_required(login_url='/accounts/login/'))
    # def dispatch(self, request, *args, **kwargs):
    #     return super(UpdateProfileView, self).dispatch(request, *args, **kwargs)


class AddComment(CreateView):
    model = PostComment
    form_class = AddCommentForm
    query_pk_and_slug = True
    slug_field = links
    slug_url_kwarg = links

    def get_success_url(self):
        return reverse('beauty:detail', args=[self.kwargs[links]])

    def form_valid(self, form):
        def current_pk():
            comment = PostComment.objects.all().order_by('-id').first()
            if comment is None:
                return 0
            return int(comment.pk)

        if not self.request.POST.get('name'):
            form.instance.name = f"Unknown User{current_pk()}"
        else:
            form.instance.name = self.request.POST.get('name')
        post = get_object_or_404(Post, link=self.kwargs['link'])
        form.instance.post = post
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.POST.get('comment'):
            return HttpResponseRedirect(reverse('beauty:detail', args=[self.kwargs[links]]))
        return super().dispatch(request, *args, **kwargs)


class ProductDetail(DetailView):
    slug_field = p_links
    slug_url_kwarg = p_links
    query_pk_and_slug = True
    model = ProductReview
    template_name = 'beauty/detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        pew = self.request.GET.get('pp')
        form = AddProductCommentForm
        this = get_object_or_404(ProductReview, p_link=self.kwargs[p_links])
        comments = ProductComment.objects.filter(product_id=this.pk)
        """ pew == 1 post and pew == 2 is products """
        if pew == '1':
            pro_post = True
        else:
            pro_post = False

        context['form'] = form
        context['comments'] = comments
        context['con'] = pro_post
        return context


class CreateProductComment(CreateView):
    model = ProductComment
    query_pk_and_slug = True
    slug_url_kwarg = p_links
    slug_field = p_links
    form_class = AddProductCommentForm

    def get_success_url(self):
        return reverse('beauty:pro-detail', args=[self.kwargs[p_links]])

    def form_valid(self, form):
        def current_pk():
            pro = ProductReview.objects.all().order_by('-id').first()
            if not pro:
                return 0
            return int(pro.pk)

        if not self.request.POST.get('name'):
            form.instance.name = f"Unknown User{current_pk()}"
        else:
            form.instance.name = form.cleaned_data['name']
        this = get_object_or_404(ProductReview, p_link=self.kwargs[p_links])
        form.instance.product_id = this.pk
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.POST.get('comment'):
            return HttpResponseRedirect(reverse('beauty:pro-detail', kwargs={'p_link': self.kwargs[p_links]}))
        return super().dispatch(request, *args, **kwargs)


class ProductList(ListView):
    model = ProductReview
    template_name = 'beauty/list.html'
    ordering = '-id'
    paginate_by = 5
    context_object_name = 'post'

    def get_queryset(self):

beauty/templates/beauty/address.html
{% extends 'base.html' %}

{% block title %} My Address List {% endblock %}

{% block content %}
<div class="row mx-auto my-5">
    <div class="col-10 col-lg-10 mx-auto bg-white py-3">
        <div class="container mt-3 bg-white">
            <div class="card border-0">
                <div class="card-body">
                    <a href="{% url 'beauty:profile' %}" class="btn btn-secondary float-center">Back</a>
                    <a href="{% url 'beauty:add-address' %}" class="btn btn-primary float-right">Add Address</a>
                </div>
            </div>
            {% for add in address %}
            <div class="card my-4">
                <div class="card-body">
                    <h5 class="card-title">{{ add }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ add.detailed_address }}</h6>
                    <div class="card-text mb-2">
                        <div class="row">
                            <div class="col-3 text-truncate">{{ add.main_address }}</div>
                        </div>
                        <br>
                        {% if add.phone %}
                        {{ add.phone }}
                        {% else %}
                        {{ add.user.user.phone }}
                        {% endif %}
                    </div>
                    <a href="{% url 'beauty:update-address' add.address_link %}" class="card-link"> Update </a>
                    <a href="{% url 'beauty:delete-address' add.address_link %}" class="card-link text-danger"> Delete <i class="bi bi-trash"></i> </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

beauty/templates/beauty/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if pro_post %}
    {{ post.title }}
{% else %}
    {{ post.p_title }}
{% endif %}
{% endblock %}

{% block style %}
{% if pro_post %}
    <meta name="keyword" content="{{ post.keyword }}">
    <meta name="description" content="{{ post.desc }}">
{% else %}
    <meta name="keyword" content="{{ post.p_keyword }}">
    <meta name="description" content="{{ post.p_desc }}">
{% endif %}
{% endblock %}

{% block content %}
<!-- modal Create Comment -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Berikan Komentar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- end modal -->

<div class="bg-pink-2">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0002.png' %}" alt="Notepad" class="img-fluid">
        {% if pro_post %}
        <p class="text-white">Posted on {{ post.date_create | date:"d M Y" }}</p>
        {% else %}
        <p class="text-white">Posted on {{ post.p_date_create | date:"d M Y" }}</p>
        {% endif %}
    </div>
</div>

<div class="container container-fluid my-5 bg-white px-0 break-text">
    <div class="card-header mt-0 mb-3">
        <a href="/" class="btn btn-info"><i class="bi bi-arrow-left-square"></i> Back to Main Menu</a>
    </div>
    <div class="row mx-auto">
        <div class="col-lg-12" id="content">
            <h2>
                {% if pro_post %}
                    {{ post.title | safe }}
                {% else %}
                    {{ post.p_title | safe }}
                {% endif %}
            </h2>
            <div class="text-justify">
                {% if pro_post %}
                    {{ post.content | safe }}
                {% else %}
                    {{ post.p_content | safe }}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="card-footer mb-5">
        <div id="comments1">
            <div class="d-flex justify-content-end position-static sticky-top">
                <a href="#collapseExample" data-toggle="collapse" class="btn btn-primary mx-1">Berikan Komentar</a>
                {% if pro_post %}
                <form action="{% url 'beauty:like' post.link %}" method="post">
                {% else %}
                <a href="{% url 'com:add-to-cart' post.p_link %}?url={% url 'beauty:pro-detail' post.p_link %}" class="btn btn-primary"> Add to Cart </a>
                <form action="{% url 'beauty:pro-like' post.p_link %}" method="post">
                {% endif %}
                    {% csrf_token %}
                    <button class="btn btn-pink mx-1">
                        <i class="bi bi-heart-fill"></i>
                        {% if pro_post %}
                        {{ post.likes }}
                        {% else %}
                        {{ post.p_likes }}
                        {% endif %}
                    </button>
                </form>

            </div>
            <div class="collapse" id="collapseExample">
                <div class="card bg-transparent card-body border-0">
                    {% if pro_post %}
                    <form action="{% url 'beauty:add-comment' post.link %}" method="post" enctype="multipart/form-data">
                    {% else %}
                    <form action="{% url 'beauty:pro-comment' post.p_link %}" method="post" enctype="multipart/form-data">
                    {% endif %}
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form | crispy }}
                        <div class="form-group">
                            <button class="btn btn-primary">Add Comment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% if comments %}
<div class="container container-fluid pb-5 bg-white px-0 break-text mb-5">
    <div class="card-header mb-5">
        <h4>Comments</h4>
    </div>
    <div class="row mx-auto" id="comments">
        <div class="col-lg-8 mx-auto">
            {% for comment in comments %}
            <div class="mt-4">
                <div class="font-weight-bold">{{ comment.name }}</div>
                <div>
                    {{ comment.comment | safe }}
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

{% block js %}
<script src="{% static 'beauty/js/config.js' %}"></script>
{% endblock %}

beauty/templates/beauty/forms.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row mx-auto my-5">
    <div class="col-10 col-lg-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="form-group">
                <button class="btn btn-primary"> Save </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    document.getElementById('id_phone').placeholder = "Fill this field if you different phone number";
</script>
{% endblock %}

beauty/templates/beauty/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
<div class="bg-pink-2">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0002.png' %}" alt="Image" class="img-fluid">
    </div>
</div>

<!-- profiles -->
<div class="py-5 bg-white mb-0">
    <div class="container">
        <div class="row mx-auto">
            <div class="col-lg-12 mx-auto">
                <h3 class="ml-3">Hi Saya {{ profile.nick_name }}</h3>
                <div class="row mx-auto">
                    <div class="col-lg-4 mx-auto">
                        <img src="{{ profile.profile_img.url }}" alt="Annisa Maharani" class="img-fluid">
                    </div>
                    <div class="col-lg-8 mx-auto">
                        <h4>{{ profile }}</h4>
                        <hr>
                        <div class="text-justify">
                            {{ profile.desc | safe }}
                        </div>
                        <hr>
                        <div class="d-flex justify-content-end">
                            {% for socmed in profile.social_media.all %}
                            <div class="item social">
                                <a href="{{ socmed.redirect }}" target="_blank"><i class="{{ socmed.social.icon }}"></i></a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row mx-auto py-5">
        <div class="col-lg-6 my-auto">
            <img src="{% static 'beauty/img/0003.png' %}" alt="Blog" class="img-fluid">
        </div>
        <div class="col-lg-6 mx-auto">
            <div class="card border-0 bg-transparent">
                <h1 class="ml-3">Latest Post</h1>
                {% for post in latest %}
                <div class="card-body">
                    <a href="{% url 'beauty:detail' post.link %}" class="text-green text-decoration-none">
                        <h3>{{ post.title }}</h3>
                        <h4 class="text-truncate">{{ post.content | safe }}</h4>
                    </a>
                    <small class="text-muted">di upload pada tanggal </small>
                </div>
                <hr>
                {% endfor %}
                <a href="" class="btn btn-aero-blue"> See All Page Post</a>
            </div>
        </div>
    </div>
</div>

<div class="row mx-auto bg-white py-5">
    <div class="col-lg-7 col-md-10 col-9  mx-auto">
        <h2 class="modal-title mb-5"> Products </h2>
        {% for prod in products %}

        {% if forloop.counter|divisibleby:2 == 0 %}
        <div class="card mb-4 mx-auto" style="max-width: fit-content;">
            <div class="row mx-auto no-gutters">
                <div class="col-lg-8 col-8 my-auto">
                    <div class="card-body">
                        <h5 class="card-title">{{ prod.p_title }}</h5>
                        <p class="card-text">{{ prod.contents | safe }}...........</p>
                        <p class="card-text">
                            <a href="{% url 'beauty:pro-detail' prod.p_link %}" class="btn btn-primary">Read More</a>
                        </p>
                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                </div>
                <div class="col-lg-4 col-4 my-auto">
                    <img src="{{ prod.p_img.url }}" alt="{{ prod.filename }}" class="img-fluid">
                </div>
            </div>
        </div>
        {% else %}

        <div class="card mb-4 mx-auto" style="max-width: fit-content;">
            <div class="row mx-auto no-gutters">
                <div class="col-lg-4 col-4 my-auto">
                    <img src="{{ prod.p_img.url }}" alt="{{ prod.filename }}" class="img-fluid">
                </div>
                <div class="col-lg-8 col-8 my-auto">
                    <div class="card-body">
                        <h5 class="card-title">{{ prod.p_title }}</h5>
                        <p class="card-text">{{ prod.contents | safe }}...........</p>
                        <div class="card-text">
                            <form action="{% url 'beauty:pro-detail' prod.p_link %}" method="get" enctype="multipart/form-data">
                                <input type="text" name="pp" value="2" hidden>
                                <button class="btn btn-primary"> Read More</button>
                            </form>
                        </div>
                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="col-lg-12 col-md-10 col-8 mx-auto">
        <div class="container">
            <div class="d-flex justify-content-end">
                <div class="row mx-auto">
                    <div class="col-lg-4 col-sm-4 col-md-4 ml-auto">
                        <a href="{% url 'beauty:pro-list' %}" class="col btn btn-aero-blue"> See All Products </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end profiles -->
{% endblock %}

beauty/templates/beauty/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}

<div class="container my-5">
    <div class="card">
        <div class="card-body text-center">
            <div class="row mx-auto my-3">
                <div class="text-center  col-3 col-lg-3 mx-auto">
                    {% if not user.user.image %}
                    <i class="fas fa-user"></i>
                    {% else %}
                    <img src="{{ user.user.image.url }}" alt="{{ user }}-profile image" class="img-fluid">
                    {% endif %}
                    <p>{{ user }}</p>

                </div>
            </div>
            <a href="{% url 'beauty:address-list' %}" class="text-decoration-none">Address</a>
            <br>
            <a href="{% url 'beauty:update-profile' %}" class="text-decoration-none">Update Profile</a>
            <br>
            <a href="{% url 'com:on-going-item' %}" class="text-decoration-none">My Ordered item</a>
            <div class="card mt-4 text-left">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="username" class="col-sm-2 col-2 col-form-label">Username : </label>
                        <div class="col-sm-10 col-10 form-control" id="username">{{ user.username }}</div>
                    </div>
                    <div class="form-group row">
                        <label for="f_name" class="col-sm-2 col-2 col-form-label">First Name : </label>
                        <div class="col-sm-10 col-10 form-control" id="f_name">{{ user.first_name}} </div>
                    </div>
                    <div class="form-group row">
                        <label for="l_name" class="col-sm-2 col-2 col-form-label">Last Name : </label>
                        <div class="col-sm-10 col-10 form-control" id="l_name">{{ user.last_name }}</div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-sm-2 col-2 col-form-label">Email : </label>
                        <div class="col-sm-10 col-10 form-control" id="email">{{ user.email }}</div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-sm-2 col-2 col-form-label">Phone Number : </label>
                        <div class="col-sm-10 col-10 form-control" id="phone">{{ user.user.phone }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

beauty/templates/beauty/sub.html
{% extends 'base.html' %}