api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', api_preview, name='home'),
    path('page', PostEndPoint.as_view(), name='post-list'),
    path('page/<int:pk>', post_detail_end_point, name='post-detail'),
    path('product', ProductEndPoint.as_view(), name='product-list'),
    path('product/<pk>', product_detail_end_point, name='pro-detail'),
    path('media', MediaEndPoint.as_view(), name='media'),
    path('media/<pk>', media_detail_emd_point, name='media-detail'),
]

backend/urls.py
from .views import *
from django.urls import path, include

app_name = 'my'

urlpatterns = [
    path('', AdminHome.as_view(), name='home'),
    path('create-post', CreatePost.as_view(), name='create'),
    path('preview/<link>', PreviewPage.as_view(), name='preview'),
    path('update/<slug:link>', UpdatePost.as_view(), name='update'),
    path('delete/<slug:link>', DeletePost.as_view(), name='delete'),
    path('profile', profile_edit, name='profile'),
]

""" media url """
urlpatterns += [
    path('media', MediaManagerView.as_view(), name='media-manager'),
    path('media/upload', MediaUpload.as_view(), name='media-upload'),
    path('media/upload/test', MediaUploadTest, name='media-upload-test'),
    path('media/delete/<pk>', MediaDelete.as_view(), name='media-delete'),
    path('media/delete-all', delete_all_media, name='delete-all'),
]

""" products url """
# urlpatterns += [
    # path('products', ProductsList.as_view(), name='products'),
    # path('products/create', CreateProducts.as_view(), name='create-product'),
    # path('products/update/<p_link>', UpdateProductPost.as_view(), name='update-product'),
    # path('products/delete/<p_link>', DeleteProductPost.as_view(), name='pr-delete'),
    # path('products/preview/<p_link>', ReviewProductsPost.as_view(), name='pr-review'),
# ]

# TODO : next urlpatterns from products
urlpatterns += [
    path('products/', include('core.urls', namespace='core'))
]

beauty_care/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from backend.sitemaps import PostSitemaps, ProductsSitemaps


sitemaps = {
    'post': PostSitemaps,
    'product': ProductsSitemaps
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('order/', include('commerce.urls', namespace='com')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
    path('wpcp-admin/', include('backend.urls', namespace="my")),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [path('', include('beauty.urls', namespace='beauty'))]

backend/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.conf import settings
import os
from os import remove, path


class MediaIcon(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class SocialMedia(models.Model):
    social = models.ForeignKey(MediaIcon, on_delete=models.CASCADE, related_name='ico')
    redirect = models.CharField(max_length=255, verbose_name="Link Social Media Kamu ")

    def __str__(self):
        return self.social.name


class Profile(models.Model):
    name = models.CharField(max_length=255, verbose_name="Nama Kamu  ")
    nick_name = models.CharField(max_length=255, default="Annisa Maharani", verbose_name="Nama Panggilan")
    desc = RichTextField(verbose_name="Deskripsi Singkat Tentang Kamu : ")
    profile_img = models.ImageField(upload_to='profile', verbose_name="Foto Profil ")
    social_media = models.ManyToManyField(SocialMedia, blank=True, verbose_name="Shared Social Media : ")

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name="Judul Posting  ")
    link = models.SlugField(max_length=255, unique=True, default='')
    content = RichTextField(verbose_name="Konten ")
    desc = models.TextField(verbose_name="Deskripsi Singkat ")
    keyword = models.TextField(verbose_name="keyword pencarian ")
    date_create = models.DateField(auto_now=True)
    date_update = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0, verbose_name='likes')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('beauty:detail', args=[self.link])


class MediaManager(models.Model):
    file = models.FileField(upload_to='manager/')

    def __str__(self):
        return str(self.file)

    def filename(self):
        return path.basename(self.file.name)

    def delete(self, using=None, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.file.name))
        super().delete(*args, **kwargs)


class ProductReview(models.Model):
    p_title = models.CharField(max_length=255, verbose_name='Nama Produk')
    p_img = models.FileField(upload_to='product/img/', verbose_name='Link Gambar Produk', default='', max_length=255)
    price = models.FloatField(verbose_name='Harga asli produk : ')
    discount = models.FloatField(verbose_name='Harga yang akan di jual <small> *optional </small>: ', null=True, blank=True)
    p_link = models.SlugField(max_length=255, unique=True)
    p_content = RichTextField(verbose_name='Content')
    p_desc = models.TextField(verbose_name='Simple Description')
    p_keyword = models.TextField(verbose_name='keyword')
    p_date_create = models.DateField(auto_now=True)
    p_date_update = models.DateField(auto_now_add=True)
    p_likes = models.IntegerField(default=0, verbose_name='likes')
    in_stock = models.BooleanField(default=True)

    def contents(self):
        return self.p_content[:50]

    def __str__(self):
        return f"{self.p_title} about {self.p_content[:60]} see more "

    def get_absolute_url(self):
        return reverse('beauty:pro-detail', args=[self.p_link])

    def get_item_add_to_cart(self):
        return reverse('com:add-to-cart', kwargs={'p_link': self.p_link})

    def get_item_remove_from_cart(self):
        return reverse('com:remove-from-cart', kwargs={'p_link': self.p_link})

    def get_reduce_item(self):
        return reverse('com:reduce-item', kwargs={'p_link': self.p_link})

    def filename(self):
        return path.basename(self.p_img.name)

    def get_item_price(self):
        if self.discount:
            return self.discount
        return self.price

    def delete(self, using=None, *args, **kwargs):
        remove(path.join(settings.MEDIA_ROOT, self.p_img.name))
        super().delete(*args, **kwargs)

backend/forms.py
from django import forms
from .models import *

soc_med = SocialMedia.objects.all()
soc_med_list = []

for sm in soc_med:
    soc_med_list.append(soc_med)


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'keyword', 'desc']

        widgets = {
            'keyword': forms.TextInput(),
            'desc': forms.TextInput()
        }


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['p_title', 'p_img', 'p_content', 'price', "discount", 'p_desc', 'p_keyword']

        widgets = {
            'p_keyword': forms.TextInput(),
            'p_desc': forms.TextInput()
        }


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

        widgets = {
            'social_media': forms.CheckboxSelectMultiple(choices=soc_med_list)
        }

backend/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views.generic import *
from .forms import *
from .utils import staff_required, slug_generator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q as __

link = 'link'
p_link = 'p_link'


class AdminHome(ListView):
    template_name = "be/home.html"
    model = Post
    context_object_name = 'post'
    ordering = '-id'
    paginate_by = 10

    def get_queryset(self):
        q = self.request.GET.get('q')
        post = Post.objects.all()
        if q is not None:
            post = Post.objects.filter(
                __(title__icontains=q) | __(content__icontains=q) |
                __(keyword__icontains=q) | __(desc__icontains=q)
            ).order_by(self.ordering)
            return post
        else:
            return post.order_by(self.ordering)

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AdminHome, self).dispatch(request, *args, **kwargs)


class CreatePost(CreateView):
    template_name = "be/create.html"
    model = Post
    form_class = CreatePostForm

    def get_success_url(self):
        return reverse('my:update', args=[self.object.link])

    def get_context_data(self, **kwargs):
        context = super(CreatePost, self).get_context_data(**kwargs)
        back = self.request.GET.get('b')

        def b_url():
            if back is not None:
                """ 1 is for post and 2 is for products """
                if back == '1':
                    return True
                else:
                    return False

        context['back'] = b_url()

        return context

    def form_valid(self, form):
        bad_chars = [';', ':', '!', "*", '!', '@', '#', '$', '%', '^', '&', '(', ')']
        _link = form.cleaned_data['title']
        _link = _link.replace(' ', '-')

        for i in bad_chars:
            if bad_chars[-3] in _link:
                _link = _link.replace(i, 'n')
            _link = _link.replace(i, '')

        while True:
            if _link[-1] == '-':
                _link = _link[:-1]
            else:
                break

        form.instance.link = _link.lower()
        return super().form_valid(form)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(CreatePost, self).dispatch(request, *args, **kwargs)


class UpdatePost(UpdateView):
    template_name = 'be/update.html'
    model = Post
    form_class = CreatePostForm
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_success_url(self):
        return reverse('my:update', args=[self.object.link])

    def form_valid(self, form):
        bad_chars = [';', ':', '!', "*", '!', '@', '#', '$', '%', '^', '&', '(', ')']
        _link = form.cleaned_data['title']
        _link = _link.replace(' ', '-')

        for i in bad_chars:
            if bad_chars[-3] in _link:
                _link = _link.replace(i, 'n')
            _link = _link.replace(i, '')

        if _link[-1] == '-':
            _link = _link[:-1]
            if _link[-1] == '-':
                _link = _link[:-1]

        form.instance.link = _link.lower()
        return super().form_valid(form)

    @method_decorator(login_required(login_url='/acconts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdatePost, self).dispatch(request, *args, **kwargs)


class DeletePost(DeleteView):
    model = Post
    template_name = "be/delete.html"
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_success_url(self):
        return reverse('my:home')

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(DeletePost, self).dispatch(request, *args, **kwargs)


class MediaManagerView(ListView):
    model = MediaManager
    paginate_by = 10
    template_name = 'be/media.html'
    ordering = ['-id']
    context_object_name = 'media'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MediaManagerView, self).get_context_data(**kwargs)

        return context

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(MediaManagerView, self).dispatch(request, *args, **kwargs)


class MediaDelete(DeleteView):
    model = MediaManager
    template_name = 'be/delete.html'
    query_pk_and_slug = True
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        return reverse('my:media-manager')

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MediaDelete, self).dispatch(request, *args, **kwargs)


class MediaUpload(CreateView):
    model = MediaManager
    template_name = 'be/media_upload.html'
    fields = "__all__"

    def get_success_url(self):
        return reverse('my:media-manager')

    def form_valid(self, form):
        form.save(commit=False)
        if self.request.FILES:
            files = self.request.FILES.getlist('file')[:-1]
            for f in files:
                self.model.objects.create(file=f)

        return super().form_valid(form)

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        if not self.request.FILES.getlist('file'):
            return redirect('my:media-manager')
        return super(MediaUpload, self).dispatch(request, *args, **kwargs)


class PreviewPage(DetailView):
    model = Post
    template_name = 'be/preview.html'
    context_object_name = 'post'
    query_pk_and_slug = True
    slug_field = link
    slug_url_kwarg = link

    def get_context_data(self, **kwargs):
        context = super(PreviewPage, self).get_context_data(**kwargs)
        page = True

        context['page'] = page
        return context

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(staff_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PreviewPage, self).dispatch(request, *args, **kwargs)


@login_required(login_url='/accounts/login/')
def MediaUploadTest(request):
    if request.method == 'POST':
        files = request.FILES.getlist('file')
        for file in files:
            print(file)

    return redirect('my:media-manager')


@login_required(login_url='/accounts/login/')
@staff_required
def delete_all_media(request):
    if request.method == 'POST':
        media = MediaManager.objects.all()
        for file in media:
            file.delete()
    return redirect("my:media-manager")


""" Profile Editing """


@login_required(login_url='/accounts/login/')
@staff_required
def profile_edit(request):
    profile = get_object_or_404(Profile, pk=1)
    form = UpdateProfileForm(request.POST or None, request.FILES or None, instance=profile)
    if form.is_valid():
        form.save()
        return redirect('my:home')

    context = {
        'form': form,
    }

    return render(request, 'be/create.html', context)

backend/templates/be/create.html
{% extends 'my.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %} Create Post {% endblock %}

{% block content %}
<div class="bg-pink">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0001.png' %}" alt="Create Post" class="img-fluid">
    </div>
</div>
<div class="container my-5">
    <div class="card">
        <div class="card-header">
            {% if back %}
                <a href="{% url 'my:home' %}" class="btn btn-info"> Back </a>
            {% else %}
                <a href="{% url 'my:core:products' %}" class="btn btn-info"> Back </a>
            {% endif %}
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {{ form.media }}
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
                    <button class="btn btn-primary"> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/be/delete.html
{% extends 'my.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %} {{ post }} - Delete Post {% endblock %}

{% block content %}
<div class="bg-pink">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0001.png' %}" alt="Create Post" class="img-fluid">
    </div>
</div>
<div class="container my-5">
    <div class="card">
        <div class="card-header">
            {% if post.link %}
                <a href="{% url 'my:home' %}" class="btn btn-info"> Back </a>
            {% else %}
                <a href="{% url 'my:core:products' %}" class="btn btn-info"> Back </a>
            {% endif %}

        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {{ form.media }}
                {% csrf_token %}
                {{ form | crispy }}
                <h1 class="text-danger">Post To Delete : </h1>
                <h5>Name : {{ post | safe }}</h5>
                <h5>Link :
                    {% if post.link %}
                        {{ post.link }}
                    {% else %}
                        {{ post.p_link }}
                    {% endif %}
                </h5>

                <div class="form-group">
                    <button class="btn btn-danger"> Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/be/home.html
{% extends 'my.html' %}
{% load static %}
{% block title %} CPanel Home {% endblock %}

{% block content %}
<div class="bg-pink">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0001.png' %}" alt="Content Creator" class="img-fluid mx-auto">
    </div>
</div>

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-end">
                <a href="{% url 'my:create' %}" class="btn btn-primary"> Create Post</a>
            </div>
        </div>
        <div class="card-body">
            <form method="get" enctype="multipart/form-data">
                <div class="row mx-auto my-3">
                    <input type="text" name="q" class="form-control col-lg-11 col-10">
                    <button class="btn btn-primary col-lg-1 col-2"><i class="bi bi-search"></i></button>
                </div>
            </form>
            {% if post %}
            <table class="mt-4 table table-responsive-lg" id="post">
                <thead class="thead-light">
                <tr>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                    <th scope="col">Handle</th>
                </tr>
                </thead>
                <tbody>
                {% for post in post %}
                <tr>
                    <td>{{ post }}</td>
                    <td>{{ post.date_create }}</td>
                    <td>
                        <form action="{% url 'my:update' post.link %}">
                            <button class="btn btn-success"> Update</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'my:delete' post.link %}">
                            <button class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    <td><a href="{% url 'my:preview' post.link %}">{{ post.link }}</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="row mx-auto">
                <div class="col-lg-10 col-10 mx-auto  mt-4">
                    <h1 class="text-dark text-center font-times-new-roman ">maaf halaman yang kamu cari tidak tersedia</h1>
                </div>
            </div>
            {% endif %}
            <div class="d-flex justify-content-center py-4">
                {% if is_paginated %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}#post"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">begin</span>
                            </a>
                        </li>
                        {% endif %}

                        {% for n in page_obj.paginator.page_range %}
                            {% if page_obj.number == n %}
                            <li class="page-item active">
                                <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                            </li>
                            {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}#post">{{ n }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}#post" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">end</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/be/media.html
{% extends 'my.html' %}
{% block title %}Media Manager{% endblock %}

{% block content %}
<!-- modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Upload a File</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'my:media-upload' %}" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="file" name="file" id="file" class="form-control-file" multiple>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary"><i class="bi bi-cloud-upload"></i> Upload</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel2">Delete All Files</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'my:delete-all' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <button class="btn btn-danger"><i class="bi bi-trash"></i> Delete All</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<!-- modal end -->

<div class="bg-transparent bg-pink">
    <div class="py-5">
        <div class="d-flex justify-content-end mb-3 row mx-auto px-2">


            <button href="" class="btn btn-primary col-sm-2 mx-2 " data-toggle="modal" data-target="#exampleModal"><i class="bi bi-cloud-upload-fill"></i> Upload Media</button>
            <button href="" class="btn btn-danger col-sm-2 mx-2" data-toggle="modal" data-target="#exampleModal2"><i class="bi bi-trash"></i> Delete All Media</button>

        </div>
        <div class="row mx-auto">
            {% for file in media %}
            <div class="col-lg-3 mb-4">
                <div class="card">
                    <div class="embed-responsive embed-responsive-16by9">
                        <img src="{{ file.file.url }}" alt="Media Image" class="img-fluid embed-responsive-item">
                    </div>
                    <div class="card-body">
                        <input type="text" name="img_link" id="img_link_{{file.pk}}" value="{{ file.file.url }}" onclick="copy({{ file.pk }})" class="form-control" >
                        <div class="row mx-auto my-3"><a href="{% url 'my:media-delete' file.pk %}" class="col btn btn-danger">Delete <i class="bi bi-trash"></i> </a></div>
                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
<script>
    function copy(lv) {
        let ids = 'img_link_' + lv;
        ids.replace(" ", "_");
        let copyText = document.getElementById(ids);
        copyText.select();
        copyText.setSelectionRange(0, 9999);
        navigator.clipboard.writeText(copyText.value);
    }

</script>
{% endblock %}

backend/templates/be/media_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {{ form.media }}
    <input type="file" name="file" id="file" class="form-control-file" multiple>
    <button type="submit">Save</button>
</form>

</body>
</html>

backend/templates/be/preview.html
{% extends 'my.html' %}
{% block title %} Preview Page {% endblock %}
{% load static %}
{% block content %}
    <div class="container container-fluid bg-white px-2 py-5 break-text my-5">
        <div class="row mx-auto">
            <div class="col-lg-12 col-12" id="content">
                <div class="text-justify">
                    {% if page %}
                    {{ post.content | safe }}
                    {% else %}
                    {{ post.p_content | safe }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'beauty/js/config.js' %}"></script>
{% endblock %}

backend/templates/be/update.html
{% extends 'my.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %} {{ post }} - Update Post {% endblock %}

{% block content %}
<div class="bg-pink">
    <div class="container d-flex flex-column align-items-center">
        <img src="{% static 'beauty/img/0001.png' %}" alt="Create Post" class="img-fluid">
    </div>
</div>
<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <div class="row mx-auto">
                <a href="{% url 'my:home' %}" class="btn btn-info col-1 col-lg-1"> Back </a>
                <div class="col-11 col-lg-11">
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'my:preview' post.link %}" class="btn btn-success " target="_blank"> Preview </a>
                    </div>
                </div>
            </div>


        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {{ form.media }}
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
                    <button class="btn btn-primary"> Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}