api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path('', api_preview, name='home'),
    path('page', PostEndPoint.as_view(), name='post-list'),
    path('page/<int:pk>', post_detail_end_point, name='post-detail'),
    path('product', ProductEndPoint.as_view(), name='product-list'),
    path('product/<pk>', product_detail_end_point, name='pro-detail'),
    path('media', MediaEndPoint.as_view(), name='media'),
    path('media/<pk>', media_detail_emd_point, name='media-detail'),
]

backend/urls.py
from .views import *
from django.urls import path, include

app_name = 'my'

urlpatterns = [
    path('', AdminHome.as_view(), name='home'),
    path('create-post', CreatePost.as_view(), name='create'),
    path('preview/<link>', PreviewPage.as_view(), name='preview'),
    path('update/<slug:link>', UpdatePost.as_view(), name='update'),
    path('delete/<slug:link>', DeletePost.as_view(), name='delete'),
    path('profile', profile_edit, name='profile'),
]

""" media url """
urlpatterns += [
    path('media', MediaManagerView.as_view(), name='media-manager'),
    path('media/upload', MediaUpload.as_view(), name='media-upload'),
    path('media/upload/test', MediaUploadTest, name='media-upload-test'),
    path('media/delete/<pk>', MediaDelete.as_view(), name='media-delete'),
    path('media/delete-all', delete_all_media, name='delete-all'),
]

""" products url """
# urlpatterns += [
    # path('products', ProductsList.as_view(), name='products'),
    # path('products/create', CreateProducts.as_view(), name='create-product'),
    # path('products/update/<p_link>', UpdateProductPost.as_view(), name='update-product'),
    # path('products/delete/<p_link>', DeleteProductPost.as_view(), name='pr-delete'),
    # path('products/preview/<p_link>', ReviewProductsPost.as_view(), name='pr-review'),
# ]

# TODO : next urlpatterns from products
urlpatterns += [
    path('products/', include('core.urls', namespace='core'))
]

beauty/urls.py
from django.urls import path
from .views import *

app_name = 'beauty'

urlpatterns = [
    path('', MainPage.as_view(), name='home'),
    path('post-list', PageListView.as_view(), name='list'),
    path('add-subs', AddSubscriber.as_view(), name='add-subs'),
    path('<link>/comment', AddComment.as_view(), name='add-comment'),
    path('<link>/like', add_likes, name='like'),
]

urlpatterns += [
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/update', UpdateProfileView.as_view(), name='update-profile'),
    path('profile/address', AddressList.as_view(), name='address-list'),
    path('profile/address/create', AddAddressView.as_view(), name='add-address'),
    path('profile/address/<slug:address_link>', UpdateAddress.as_view(), name='update-address'),
    path('profile/address/<slug:addderss_link>/delete', AddressDelete.as_view(), name='delete-address'),
]

urlpatterns += [
    path('products', ProductList.as_view(), name='pro-list'),

]

""" URL for Page detail """
urlpatterns += [
    path('product/<p_link>/comment', CreateProductComment.as_view(), name='pro-comment'),
    path('product/<p_link>/like', pro_likes, name='pro-like'),
    path('product/<p_link>', ProductDetail.as_view(), name='pro-detail'),
    path('<link>', PageDetail.as_view(), name='detail'),
]

beauty_care/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap
from backend.sitemaps import PostSitemaps, ProductsSitemaps


sitemaps = {
    'post': PostSitemaps,
    'product': ProductsSitemaps
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('download/<path>', serve, settings.MEDIA_ROOT),
    path('accounts/', include('allauth.urls')),
    path('order/', include('commerce.urls', namespace='com')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
    path('wpcp-admin/', include('backend.urls', namespace="my")),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [path('', include('beauty.urls', namespace='beauty'))]

commerce/urls.py
from django.urls import path
from .views import *

app_name = 'com'

urlpatterns = [
    path('', OrderSummary.as_view(), name='order'),
    path('add-to-cart/<p_link>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<p_link>', remove_from_cart, name='remove-from-cart'),
    path('reduce/<p_link>', reduce_item, name='reduce-item'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('payment/success/<int:pk>', PaymentSuccess.as_view(), name='payment-success'),
    path('payment/cancel', PaymentCancel.as_view(), name='payment-cancel'),
    path('payment/<method>', PaymentView.as_view(), name='payment'),
    path('webhook/stripe', stripe_webhook, name='stripe-webhook')
]

""" url for ordered item """

urlpatterns += [
    path("ordered", MyOrderedItem.as_view(), name="ordered-item"),
    path('ordered/on-going', MyOngoingItem.as_view(), name='on-going-item'),
    path('ordered/ship/<slug:reff>', SeeReceipt.as_view(), name='receipt-detail'),
]

templates/base.html
<!doctype html>
<html lang="en-US">
{% load static %}
{% load i18n %}
{% load cart_template_tags %}
{% load l10n %}
{% load tz %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'beauty/css/config.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <title>{% block title %}{% endblock %} - Beauty Care</title>

    <meta name="robots" content="index,follow" />
    <meta name="author" content="focus digital design" />
    <meta name="distribution" content="global" />
    <meta name="revisit-after" content="1 days" />
    <meta name="googlebot" content="index,follow" />
    <meta name="msnbot" content="index,follow" />
    <meta name="yahoobot" content="index,follow" />
    <meta name="spiders" content="all" />
    <meta name="webcrawlers" content="all" />
    {% block style %}
    {% endblock %}
</head>

<body>

<!-- modal search -->
<!-- Modal Pencarian blog　-->
<div class="modal fade" id="modalSearch" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Pencarian Laman Blog</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'beauty:list' %}" method="get">
                    <div class="form-group">
                        <label for="searchInput">Search</label>
                        <input type="text" name="q" id="searchInput" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">Search</button>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- modal pencarian halaman prodiuk-->
<div class="modal fade" id="modalSearch2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Pencarian Laman Produk</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'beauty:pro-list' %}" method="get">
                    <div class="form-group">
                        <label for="searchInput">Search</label>
                        <input type="text" name="q" id="searchInput" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">Search</button>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- end modal -->

<!-- modal message -->
<div class="modal fade" id="modalSearch3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> Pesan </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% for msg in messages %}
                {{ msg }}
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- end modal message-->

<!-- navabr -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">

    <a class="navbar-brand" href="/">Beauty Care</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
                <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'beauty:list' %}" class="nav-link"> Post List</a>
            </li>
            <li class="nav-item">
               <a href="{% url 'beauty:pro-list' %}" class="nav-link"> Product List</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pencarian
                </a>
                <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="nav-link" href="#modalSearch" data-toggle="modal">Cari Halaman Blog <i class="bi bi-search"></i></a>
                    <a class="nav-link" href="#modalSearch2" data-toggle="modal">Cari Halaman Produk <i class="bi bi-search"></i></a>
                </div>
            </li>
            <li class="nav-item"><a href="{% url 'beauty:profile' %}" class="nav-link">MyAccount <i class="fas fa-user"></i></a></li>
            <li class="nav-item">
                <a href="{% url 'com:order' %}" class="nav-link"><i class="bi bi-cart2"></i> {{ request.user | cart_item_counter }} </a>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <a href="/accounts/logout/" class="text-danger mr-0"> Logout </a>
        {% else %}
        <a href="/accounts/login/" class="text-success mr-0"> Login </a>
        {% endif %}
    </div>

</nav>

{% block content %}
{% endblock %}

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>

{% if messages %}
<script type="text/javascript">
    $('#modalSearch3').modal('show');
</script>
{% endif %}

{% block js %}
{% endblock %}

</body>

</html>

templates/footer.html
{% load static %}
<footer>
    <div class="card">
        <div class="card-body">
            <div class="py-5" id="footer">
                <div class="container">
                    <div class="row mx-auto">
                        <div class="col-lg-3 mt-4 mx-auto">
                            <h4>Resource</h4>
                            <div class="d-flex flex-column">
                                <a href="https://freepik.com">FreePik.com</a>
                                <a href="https://sman33hebat.wixsite.com/sman33jkt">SMAN 33 Jakarta</a>
                                <a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/">Bootstrap
                                    @4.6</a>
                            </div>
                        </div>
                        <div class="col-lg-3 mt-4 mx-auto">
                            <h4>Lokasi</h4>
                            <a href="https://www.google.com/maps/place/State+Senior+High+School+33+Jakarta/@-6.1492551,106.7247803,17z/data=!3m1!4b1!4m5!3m4!1s0x2e6a1d53d9640c83:0xaeee76439cf3b23a!8m2!3d-6.1492551!4d106.726969"
                               class="text-decoration-none" target="_blank">
                                <img src="{% static 'beauty/img/sman_33.jpg' %}" alt="IT PLN Jakartas"
                                     class="img-fluid">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="footer2" class="bg-primary text-center text-white pt-3 pb-3">
        Created by <a href="https://www.instagram.com/an.maharans/" class="text-white">Annisa</a>
        <br>
        2021<sup>&copy;</sup>
    </div>
</footer>

templates/my.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load l10n %}
{% load tz %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'beauty/css/config.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'my:home' %}">Cpanel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/wpcp-admin/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my:media-manager' %}">Media</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'my:core:products' %}">Products List</a>
                    <form action="{% url 'my:core:create-product' %}" method="get" enctype="multipart/form-data">
                        <input type="text" name="b" id="b" value="2" hidden>
                        <button class="dropdown-item">Create Product Post</button>
                    </form>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>

            <li class="nav-item">
                <form action="{% url 'my:create' %}" method="get" enctype="multipart/form-data">
                    <input type="text" name="b" value="1" hidden>
                    <button class="nav-link btn btn-link" href="">Create Post</button>
                </form>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my:profile' %}">Edit Profile</a>
            </li>
            <li class="nav-item"><a href="{% url 'my:core:on-going-list' %}" class="nav-link">Ordered</a></li>
        </ul>
        {% if user.is_authenticated %}
        <a class="mr-0 text-danger navbar-brand" href="/accounts/logout/">Logout</a>
        {% endif %}
    </div>
</nav>
{% block content %}
{% endblock %}

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
{% block scripts %}
{% endblock %}

</body>
</html>

templates/test.html
<!doctype html>
<html lang="en">
{% load static %}
{% load i18n %}
{% load l10n %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'beauty/css/config.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <title>Hello, world!</title>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a href="" class="navbar-brand">Beauty Care</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
                <a class="nav-link" href="/book/">List Buku</a>
                <a class="nav-link" href="/my/">Unggah Buku</a>
                <a class="nav-link  " href="/maps/">Peta Perpustakaan</a>
                <a class="nav-link font-weight-bold text-info" href="/accounts/login/">Login</a>
                <a class="nav-link font-weight-bold text-success" href="/accounts/signup/">Register</a>
            </div>
        </div>
    </div>
</nav>

<div class="bg-pink">
    <div class="row py-3">
        <div class="col-lg-12 mx-auto">
            <img src="{% static 'beauty/img/2011.jpg' %}" alt="Image" class="img-fluid">
        </div>
        <div class="col-lg-4 py-4 mx-auto">
            <div class="justify-content-center">
                <h1 class="font-weight-bold mx-auto">Beauty Care</h1>
                <p>Kecantikan tidak hanya dilihat dari wajah saja, maka dari itu mari kita menjadi cantik secara
                    keseluruhan</p>
            </div>
        </div>
    </div>
</div>

<div class="container bg-transparent my-5">
    <div class="row">
        <div class="col-lg-4">
            <img src="{{ profile.profile_img.url }}" alt="" class="img-fluid">
        </div>
        <div class="col-lg-8">
            <div class="card border-0">
                <div class="card-body">
                    <h2>{{ profile }}</h2>
                    <hr>
                    {{ profile.desc | safe }}
                    <hr>
                    <div class="item social">
                        {% for i in profile.social_media.all %}
                        <a href="{{ i.redirect }}" target="_blank"><i class="{{ i.social.icon }}"></i></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

</body>
</html>